### ISSUE TITLE
How to open triggerbot tab, aimbot.?

### ISSUE THREAD

**Issue by Andriuxas** [EasyHax/EasySharp#1]
How to open triggerbot tab, aimbot.? I can open skin changer but not triggerbot or aimbot etc tab. help me. Where i can find it?

**Comment by EasyHax** [comment]
The tab has been purposely removed because the features are not even coded.
If you want to add aimbot, wallhack, triggerbot, you have to code it yourself.

**Comment by Andriuxas** [comment]
Okay..

**Comment by Andriuxas** [comment]
I want to ask some questions in pm. 𝓐𝓷𝓭𝓻𝓲𝓾𝔁𝓪𝓼#3868

**Comment by Andriuxas** [comment]
Add me..

**Comment by Andriuxas** [comment]
Can u also add triggerbot and chams it will be best external cheat open source.

**Comment by Andriuxas** [comment]
huh?

**Comment by EasyHax** [comment]
I won't add anything unless I start to write csgo cheats again
But I still answer questions, EasyHax#2639 is my Discord
